# Generated by Django 5.2.6 on 2025-11-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='fecha',
            new_name='mes',
        ),
    ]
