# Generated by Django 5.2.6 on 2025-11-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_fecha_pago_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
